### ISSUE TITLE
SYSTEMDRIVe = C

### ISSUE THREAD

**Issue by djibe** [varhub/chkdsk-all#1]
Hi,
why do you set system drive instead of using system var %systemdrive% ?

thx for the script

**Comment by varhub** [comment]
Hi @djibe , and sorry by my extremely late reply. I guess I readed it at mobile and never took any action.
The reason is simple: a lack of knowledge. So thanks for the tip!
Adding it...

**Comment by djibe** [comment]
Hi, thx for your feedback.
